### PR TITLE
fix (ios): Add check for nil values before adding to subviews in iOS Google Maps

### LINKED ISSUE #5217: [Expo SDK 52] App creashes with error "NSInvalidArgumentException  *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil"
### Summary

In some way, I think this issue may be related to https://github.com/react-native-maps/react-native-maps/issues/5206 and https://github.com/react-native-maps/react-native-maps/issues/5214

After upgrading to SDK 52, I'm getting an issue when I remove and add new markers.

In my app, I could remove all the code unrelated to this issue, and get this small version of the "Map" component, where I can still reproduce the error. I will add a video in the comments, so you see how to reproduce it (you have to play around with the zoom).

I migrated that code to a Expo Snack, but you won't be able to reproduce it from the snack, because iOS seems to be broken with SDK 52.

Here is the SNACK: https://snack.expo.dev/@brodanoel/react-native-maps-not-working

### Reproducible sample code

```TSX
import { useState } from 'react';
import MapView, { Marker } from 'react-native-maps';

const getZoom = region => Math.round(Math.log(360 / region.longitudeDelta) / Math.LN2);

const initialRegion = {
  latitude: -31.4205589,
  latitudeDelta: 0.5,
  longitude: -64.1734649,
  longitudeDelta: 0.5,
};

const clusters = [
  { coordinate: { latitude: -31.42, longitude: -64.185 }, i: 'aaa' },
  { coordinate: { latitude: -31.439, longitude: -64.128 }, i: 'bbb' },
];

const Map = () => {
  const [pointsToShow, setPointsToShow] = useState([]);

  const onRegionChange = currentRegion => {
    const zoom = getZoom(currentRegion);

    if (zoom >= 12) {
      setPointsToShow([]);
    } else {
      setPointsToShow(clusters);
    }
  };

  return (
    <MapView
      style={{ flex: 1 }}
      provider="google"
      onRegionChangeComplete={onRegionChange}
      initialRegion={initialRegion}
    >
      {pointsToShow.map(point => {
        return <Marker key={point.i} pinColor="red" coordinate={point.coordinate} />;
      })}
    </MapView>
  );
};

export default Map;

```

### Steps to reproduce

You should get the error while zooming in and out. Please wait for the video that I'm gonna add in the comments

### Expected result

App not crashing

### Actual result

App crashes and get closed

### React Native Maps Version

1.18.0 and 1.20.0

### What platforms are you seeing the problem on?

iOS (Google Maps)

### React Native Version

0.76.2

### What version of Expo are you using?

SDK 52 with New Architecture enabled

### Device(s)

iPhone 13 mini

### Additional information

None

### PR DESCRIPTION
**Pull request by CamBowes**
Adds `nil` checks before pushing new subviews in iOS - Fixes #5217 

### Does any other open PR do the same thing?

N/A - No prior PR raised

### What issue is this PR fixing?

#5217 - *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil issue

### How did you test this PR?

Tested in iOS Real Device & Simulator - Expo 52/RN 0.76.2 (New Architecture Enabled) (Google Maps)

### CODE REVIEW

**Comment by BrodaNoel** [comment]
Niiiiice, maaan!

Have you tried it, right?
If this fixes the problem, I can create a patch in my project and test it on production.

**Comment by Willham12** [comment]
With your patch ig got the following error @ line 192:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM insertObject:atIndex:]: index 3 beyond bounds [0 .. 1]'

**Comment by CamBowes** [comment]
I tested my issue and it had fixed the crash @Willham12 ill see if i can fix your issue in this PR too

**Comment by CamBowes** [comment]
@Willham12 can you give my latest commit a go please

**Review by Gatkins343 — APPROVED** [review]

**Comment by BrodaNoel** [comment]
While we wait for this to be merge and deployed, does somebody tried it in production? Is this fix solving the problem?
This bug is blocking my release since 2 weeks ago, so, if somebody tried it and it works, I'll create a PATCH today and test it.

**Comment by techied** [comment]
I tried this patch but I'm seeing strange behavior with markers not appearing or their props not updating correctly

**Comment by FaithfulAudio** [comment]
@Gatkins343 Hello Sir! This issue is a serious crashing bug on the library for iOS and is the source of several outstanding issues as most users don't know how to dig into XCODE errors occurring to find the sub view issues on re-render. Do you know when this has time time to be reviewed?

**Comment by BrodaNoel** [comment]
For now, the only workaround I found is to disable NewArch

**Comment by myousufrtss** [comment]
I also noticed the logs: 
Google Maps SDK for iOS version: 8.4.0.0
New version of Google Maps SDK for iOS available: 9.1.1.0, may upgrading will fix it?

**Comment by techied** [comment]
> @techied - hey, did you found a way to make markers to appear?

Unfortunately no, this is currently blocking our upgrade to new arch

**Review by FaithfulAudio — APPROVED** [review]

**Comment by FaithfulAudio** [comment]
Who are the approving reviewers to get this shipped out?

**Pull request closed without merging**
