### PR TITLE
Fix crash on iOS Apple Maps when loading really large polylines

### PR DESCRIPTION
**Pull request by ascherkus**
Switch to using heap allocation to prevent corrupting the stack.

### Does any other open PR do the same thing?

No.

### What issue is this PR fixing?

No issue filed -- discovered through our own crash monitoring software.

### How did you test this PR?

With iOS and Apple Maps load a `<Polyline>` with ~60,000 coordinates and test on a real device (does not seem to crash on iOS Simulator) and deploy / launch debugger using Xcode.

Set a breakpoint in AIRMapPolyline.m on setCoordinates().

As soon as the CLLocationCoordinate2D coords array is allocated continuing execution raises a EXC_BAD_ACCESS since the stack has been corrupted.

Switching to heap allocating the temporary coords array allows the polyline to render.

Does not affect Android / Google Maps as that code uses GMSMutablePath and calls addCoordinate in a loop (which presumably is heap allocated under the hood).

### CODE REVIEW

**Review by bhishaksanyal — APPROVED** [review]

**Comment by hamaron** [comment]
This is a very good catch. Good job, @ascherkus! I hope this PR gets merged soon.

**Comment by ascherkus** [comment]
Can someone with write access take a look at this PR?

**Comment by ascherkus** [comment]
Rebased my PR on top of latest branch -- would love to get this into the next release if possible. Let me know what's missing or what else I should look at to get this merged. Thanks!

**Review by the-habu — COMMENTED** [review]
Very nice optimization.

@Simon-TechForm I do not want to approve, as I am no (objective) c expert, but to upvote.

**Review by bhishaksanyal — APPROVED** [review]

**Comment by the-habu** [comment]
@ascherkus any chance we can get that PR rolling again?

**Comment by ascherkus** [comment]
> @ascherkus any chance we can get that PR rolling again?

Not sure what else to do here -- it's rebased, reviewed, but I can't merge as it's missing one approving review.

**Comment by Simon-TechForm** [comment]
Hello @ascherkus.

I sincerely apologize for the late reponse to this pr. The very limited time I've had to spend on this project was put towards migrating to the new react-native arch.

I'll test out the proposed changes immediately.

**Review by Simon-TechForm — APPROVED** [review]

**Pull request merged**
