### PR TITLE
Zoom controls programatically

### PR DESCRIPTION
**Pull request by julienR2**
### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

It exposes zoom controls through map methods (zoomIn, zoomOut, zoomTo, zoomBy)

### How did you test this PR?

Android only for now, tested on a virtual device (Nexus 5x), creating an example.

### CODE REVIEW

**Comment by julienR2** [comment]
Hope to add the IOS version (and hopefully a MapKit solution as well using this solution https://stackoverflow.com/questions/41639478/mkmapview-center-and-zoom-in#answer-41639538) soon !

**Comment by dbyilmaz** [comment]
+1

**Comment by julienR2** [comment]
Hi ! Sorry I was away for my project on react native for few months, so I couldn't give the IOS implementation a try..
Hopefully I'll be able within the next month, but if anyone more fluent with IOS wants to go for it, it would be welcomed !

**Comment by BrodaNoel** [comment]
Any plans to merge this one?

**Comment by julienR2** [comment]
We can probably go ahead and close this as it has been implemented long time ago and I havent' check if it still compatible with the last changes..
Initially I wanted to port it to IOS too before merging, but I never took the time unfortunately 😕 
If anyone want to take over this I can help through the process, even though it should be quite straightforward, otherwise I'd recommend to close it.

**Comment by julienR2** [comment]
Thanks @rborn
Hopefully I can take some time soon to be more active on this repo again 🤞

**Pull request closed without merging**
