### PR TITLE
fix: fix AnimatedRegion types

### PR DESCRIPTION
**Pull request by mateki0**
### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

https://github.com/react-native-maps/react-native-maps/issues/4843
https://github.com/react-native-maps/react-native-maps/issues/4778

### How did you test this PR?

- It should affect only types, not the functionality.
- I've tested it on: iOS simulator (iPhone 12), Android real device (Samsung M23)
- I wasn't able to test it on iPhone real device

It should work as it is now on both platforms. However I have problem on Android connected with this code because _component is undefined. If i remove **_component** and leave **this.marker.animateMarkerToCoordinate(newCoordinate, 500)** it works fine.

```tsx
// example/src/examples/AnimatedMarkers.tsx

animate() {
   ...
    if (Platform.OS === 'android') {
      if (this.marker) {
        this.marker._component.animateMarkerToCoordinate(newCoordinate, 500);
      }
    } 
  }
```

On iOS nothing happens after pressing Animate button, but I didn't want to fix it here because it was working the same before my changes and it is already reported in another [issue](https://github.com/react-native-maps/react-native-maps/issues/4860). And it should be fixed in separate pull request

### CODE REVIEW

**Review by salah-ghanim — CHANGES_REQUESTED** [review]
@mateki0  why not extend Region type instead ? we can avoid duplication and in the future if Region object changes AnimatedRegion will be equally updated which is what we want.

**Comment by mateki0** [comment]
@salah-ghanim I'm not sure if it's what you meant but I've updated region type in MapView.tsx instead of making changes in AnimatedRegion itself

**Review by FawadAhmad001 — APPROVED** [review]

**Comment by salah-ghanim** [comment]
@mateki0 please rebase the branch on master so that I merge this type fix.

**Comment by mateki0** [comment]
> @mateki0 please rebase the branch on master so that I merge this type fix.

Hi, I just did it, thanks for merging

**Comment by salah-ghanim** [comment]
@mateki0 please rebase again so that I finally merge this as well.

**Comment by mateki0** [comment]
@salah-ghanim done :)

**Comment by salah-ghanim** [comment]
@mateki0 your branch is out of date again

**Comment by brianbowden** [comment]
Always love it when a fix gets released just in time for me to need it. :) Thanks for the effort here!

**Pull request merged**
