### PR TITLE
feat: react-native-windows map support

### PR DESCRIPTION
**Pull request by colincarter**
### Does any other open PR do the same thing?

(please answer here)

### What issue is this PR fixing?

(please link the issue here)

### How did you test this PR?

(please answer here)

### CODE REVIEW

**Comment by salah-ghanim** [comment]
@colincarter what's your plan here? what windows / macos native libraries you want to use to render maps ?

**Comment by colincarter** [comment]
@salah-ghanim  I hadn't realised a PR would automatically be created.  It's a bit too early at this stage.  I have a react-native-windows version of react-native-maps working in production.  It covers a limited api subset MapView, Marker, Callout, Polygon and Polyline.  I've been using windows UWP [MapControl](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.maps?view=winrt-22621) apis.  It's written in C# at the moment but I intend to convert it to C++

**Comment by salah-ghanim** [comment]
@olincarter sounds very good, might be worth it to publish your own version separately for a while to see if there is community traction ? also please checkout https://github.com/react-native-maps/react-native-maps/discussions/4975

**Comment by colincarter** [comment]
Closing this PR as not ready

**Pull request closed without merging**
