### PR TITLE
fix(example): fix typo in AndroidManifest.xml for ACCESS_COARSE_LOCATION permission

### PR DESCRIPTION
**Pull request by fish-can**
### Does any other open PR do the same thing?

I don't see a similar PR

### What issue is this PR fixing?

have a typo in example project #4879

### How did you test this PR?

no test, just referencing Android Manifest.permission

https://developer.android.com/reference/android/Manifest.permission#ACCESS_COARSE_LOCATION

### CODE REVIEW

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]
LGTM

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]
LGTM

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]
LGTM

**Review by GETAWAY-Dev — APPROVED** [review]

**Comment by salah-ghanim** [comment]
Approved

**Review by salah-ghanim — APPROVED** [review]
LGTM

**Comment by fish-can** [comment]
What happened?
Is there anything I can improve?

**Review by salah-ghanim — APPROVED** [review]

**Comment by salah-ghanim** [comment]
@fish-can unfortunately I can't merge pull requests for some reason, trying to contact other maintainers to find out what's going on.

**Pull request merged**
