### PR TITLE
Android:Fix fitToCoordinates with preset mapPadding (#3308)

### PR DESCRIPTION
**Pull request by hosle**
### Does any other open PR do the same thing?

NO

### What issue is this PR fixing?

#3308 

### How did you test this PR?

Just verify it by following steps : 

1. Set mapPadding to the `MapView` in `example/examples/FitToCoordinates.js:69`, such as 
```
<MapView
...
mapPadding={{ left: 15, top: 0, right: 0, bottom: 60 }}
...
>
```
2. Run the demo app from this PR on Android
3. Enter `Fit Map To Coordinates`, you can see the Google watermark is located with padding.
4. Click Btn `Fit Bottom Two Markers with Padding`
5. Camera zooms in those two Markers while Google watermark keeps in the same position instead of moving to the initial pos.
6. Problem solved

### CODE REVIEW

**Comment by rborn** [comment]
Hi @hosle thanks for the PR 😻

Is iOS suffering form the same issue ? And if yes maybe you could also have a look?  😅

**Comment by hosle** [comment]
> Hi @hosle thanks for the PR 😻
> 
> Is iOS suffering form the same issue ? And if yes maybe you could also have a look? 😅

Hi @rborn , iOS works well as expected. With this fix, android will be aligned with iOS.

**Comment by rborn** [comment]
😻

**Comment by 0nlyDev** [comment]
> ### Does any other open PR do the same thing?
> NO
> 
> ### What issue is this PR fixing?
> #3308
> 
> ### How did you test this PR?
> Just verify it by following steps :
> 
> 1. Set mapPadding to the `MapView` in `example/examples/FitToCoordinates.js:69`, such as
> 
> ```
> <MapView
> ...
> mapPadding={{ left: 15, top: 0, right: 0, bottom: 60 }}
> ...
> >
> ```
> 
> 1. Run the demo app from this PR on Android
> 2. Enter `Fit Map To Coordinates`, you can see the Google watermark is located with padding.
> 3. Click Btn `Fit Bottom Two Markers with Padding`
> 4. Camera zooms in those two Markers while Google watermark keeps in the same position instead of moving to the initial pos.
> 5. Problem solved

Hi,
I can't even find the file 
example/examples/FitToCoordinates.js

I am trying to solve the padding issue where the logo disappears if i add bottom padding

**Pull request merged**
