### PR TITLE
RN 0.68 and Example working again

### PR DESCRIPTION
**Pull request by salah-ghanim**
### Does any other open PR do the same thing?
NO

### What issue is this PR fixing?

- update RN to 0.68 in lib and example
- update typescript to 4.6.3
- fix dependencies for the example (include deprecated-react-native-prop-types)
- remove package-lock.json (use yarn only for example)
- example is working again 

### How did you test this PR?
- on master run react-native start
- react-native run-android

then on this branch do the same
it will be clear that master is stuck with an exception regarding React inconsistency. nothing will be displayed and the console will be spammed with error messages.

### CODE REVIEW

**Comment by Simon-TechForm** [comment]
Nice work @salah-ghanim :) Can I have you branch out of the beta branch and open the PR against the beta branch as well? (In your other PR's as well? Again, nice work). I've added a contributing file to the beta branch that describes the need for following conventional commit messages :)

**Comment by Simon-TechForm** [comment]
Nice work @salah-ghanim :) Can I have you branch out of the beta branch and open the PR against the beta branch as well? (In your other PR's as well? Again, nice work). I've added a contributing file to the beta branch that describes the need for following conventional commit messages :)

**Comment by Simon-TechForm** [comment]
@salah-ghanim If you work out the conflicts, I will be happy to have a look at this :)

Why are you deleting the root yarn.lock file?

**Comment by salah-ghanim** [comment]
@Simon-TechForm now updated ... it took some effort to make sure it's working on both android and iOS

**Pull request closed without merging**
