### PR TITLE
Feature: GeoJSON Marker Title Prop & A bit Refactor

### PR DESCRIPTION
**Pull request by WrathChaos**
### Does any other open PR do the same thing?

No other PR has the same thing

### What issue is this PR fixing?

No issue right there, directly a fix and a new feature.

### How did you test this PR?

Tested on both iOS and Android with both simulators and real devices.

# What to do

## New Feature 

- `GeoJSON` has the new prop option: `title` which shows a default `Callout` with the title.
- A bit of code refactoring for props. It has a de-construction for better code maintainability.

### CODE REVIEW

**Comment by WrathChaos** [comment]
@christopherdro, Actually I could not find the linter error. Can you help me to find it to pass from CI.

**Comment by christopherdro** [comment]
@WrathChaos please update the docs and types for this new props. I’ll take a closer look at the error on CI

**Comment by WrathChaos** [comment]
@christopherdro,
 I updated the doc, should I update anywhere else?

**Comment by christopherdro** [comment]
@WrathChaos Here as well please. https://github.com/react-native-maps/react-native-maps/blob/master/index.d.ts#L598-L611

**Comment by WrathChaos** [comment]
@christopherdro Done :)

**Comment by christopherdro** [comment]
@WrathChaos I made a mistake while trying to fix the lint errors. Can you push force push your the changes for branch `Feature/GeoJSONTitle` that you have locally back to your fork?

**Comment by WrathChaos** [comment]
@christopherdro Done

**Comment by WrathChaos** [comment]
@christopherdro When do you think this and the other PR's will be on live?

**Comment by christopherdro** [comment]
@WrathChaos Can't say for sure right now, but one option is to point to your fork and create a branch with whatever changes you want on top of the latest stable release.

**Pull request merged**
