### PR TITLE
Android - Use double on `setCamera` to fix zoom precision. 

### PR DESCRIPTION
**Pull request by ArshanKhanifar**
### Does any other open PR do the same thing?
No, no other PRs deal with Camera Zoom. 

### What issue is this PR fixing?
It is fixing issue #3725 on Android devices. It is pretty simple. 

### How did you test this PR?
* I tested this PR in my own little project. The fix is so minimal that I didn't really see it necessary to create an online sample. If you'd like me to make a sample code, I'd happily do it.
* It's tested on a Google Pixel 4a phone. 
* I haven't tried iOS, this wouldn't affect iOS anyways.

### CODE REVIEW

**Review by christopherdro — APPROVED** [review]

**Comment by Shahriar87** [comment]
@christopherdro Hey it looks like this issue was fixed but was never released. We are facing this exact problem and I think this fix would solve it for us. Can this fix be release?

**Comment by ArshanKhanifar** [comment]
@Shahriar87 in the meantime you can directly install from master, though Idk how stable it is:
```
yarn add https://github.com/react-native-maps/react-native-maps/
```

**Comment by Shahriar87** [comment]
Ya, we are also concerned about how stable would that be.

**Comment by christopherdro** [comment]
I will prepare a pre-release of v0.29.0 shortly that will include these changes. However, that is going to include everything that's currently on master. You can always fork the repo and cherry-pick this commit on top of your current version and create your own branch. Then you can update `react-native-maps` to pull from your branch in package.json instead of a published version number.

**Pull request merged**
