### PR TITLE
docs(circle): Remove geodesic prop description from circle docs [take II]

### PR DESCRIPTION
**Pull request by jan-kozinski**
### Does any other open PR do the same thing?

This is take 2 of PR https://github.com/react-native-maps/react-native-maps/pull/4878 with base branch set to master instead of beta.

I don't see a similar PR

### What issue is this PR fixing?
not exactly fixing the issue, but found out the docs are misleading thanks to a code snippet provided in this issue.
[Typescript errors #4877](https://github.com/react-native-maps/react-native-maps/issues/4877)

### How did you test this PR?

tried to add geodesic support to MapCircle.java, found out circle doesn't support gedesic.

### CODE REVIEW

**Comment by jan-kozinski** [comment]
@salah-ghanim this is take 2 of https://github.com/react-native-maps/react-native-maps/pull/4878

**Review by salah-ghanim — APPROVED** [review]

**Comment by salah-ghanim** [comment]
@jan-kozinski it seems like you need to rebase your pull request I'm unable to merge because: This branch is out-of-date with the base branch

**Comment by jan-kozinski** [comment]
done @salah-ghanim

**Comment by jan-kozinski** [comment]
Hi @salah-ghanim , can we merge this PR? :D

**Comment by salah-ghanim** [comment]
@jan-kozinski can you please rebase one more time ? send me an email afterwards so that I merge it immediately.

**Comment by jan-kozinski** [comment]
Done :) can you please resubmit your comments on PR
https://github.com/react-native-maps/react-native-maps/pull/4905?

pt., 12 sty 2024 o 15:08 Salah Ghanim ***@***.***> napisał(a):

**Pull request merged**
