### PR TITLE
feat: refactored podspec

### PR DESCRIPTION
**Pull request by pinpong**
Does any other open PR do the same thing?
No

What issue is this PR fixing?
Fixed auto link warning message

How did you test this PR?
Tested on IOS & Android devices with example project

### CODE REVIEW

**Comment by pinpong** [comment]
@Simon-TechForm looks like you the man for the review

**Review by Willham12 — APPROVED** [review]

**Comment by Simon-TechForm** [comment]
Thank you for your contribution 👍 Having a simpler iOS setup would be nice. Since this is a breaking change, I will have a closer look at it when preparing the next major version :)

**Comment by pinpong** [comment]
with latest commit this is working with `use_frameworks! :linkage => :static`

https://github.com/react-native-maps/react-native-maps/issues/4434
https://github.com/react-native-maps/react-native-maps/discussions/4389

**Comment by giautm** [comment]
While I testing this PR with `patch-package`, I found an issue. If we rename the pod's name. It causes the expo integration break. Because the pod was not found. We shouldn't rename the pod, or the expo has to update its plugin.

https://github.com/expo/expo/blob/main/packages/%40expo/config-plugins/src/ios/Maps.ts#L108-L117

**Comment by giautm** [comment]
This is the patch and the plugin to fix expo config

Filename: `patches/react-native-maps+1.3.2.patch`
```diff
diff --git a/node_modules/react-native-maps/RNMaps.podspec b/node_modules/react-native-maps/RNMaps.podspec
new file mode 100644
index 0000000..5e9415e
--- /dev/null
+++ b/node_modules/react-native-maps/RNMaps.podspec
@@ -0,0 +1,34 @@
+require 'json'
+
+package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
+
+Pod::Spec.new do |s|
+	s.name         = "RNMaps"
+	s.version      = package['version']
+	s.summary      = package["description"]
+	s.authors      = package["author"]
+	s.homepage     = package["homepage"]
+	s.license      = package["license"]
+	s.platform     = :ios, "11.0"
+
+	s.source       = { :git => "https://github.com/react-native-maps/react-native-maps.git", :tag=> "v#{s.version}" }
+	s.source_files  = "ios/AirMaps/**/*.{h,m}"
+
+	s.dependency 'React-Core'
+	s.static_framework = true
+
+	if defined?($RNMapsWithGoogleMapsSupport) && ($RNMapsWithGoogleMapsSupport == true)
+		Pod::UI.puts "#{s.name}: GoogleMaps support enabled"
+		s.subspec 'RNGoogleMaps' do |sp|
+			sp.name         = "RNMapsGoogleMapSupport"
+			sp.platform     = :ios, "13.0"
+
+			sp.source_files  = "ios/AirGoogleMaps/**/*.{h,m}"
+			sp.compiler_flags = '-DHAVE_GOOGLE_MAPS=1', '-DHAVE_GOOGLE_MAPS_UTILS=1', '-fno-modules'
+			sp.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
+			sp.dependency 'React-Core'
+			sp.dependency 'GoogleMaps', '7.1.0'
+			sp.dependency 'Google-Maps-iOS-Utils', '4.1.0'
+		end
+	end
+end
diff --git a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMap.m b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMap.m
index 8a4215c..555f03c 100644
--- a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMap.m
+++ b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMap.m
@@ -25,10 +25,10 @@
 #import <objc/runtime.h>
 
 #ifdef HAVE_GOOGLE_MAPS_UTILS
-#import <Google-Maps-iOS-Utils/GMUKMLParser.h>
-#import <Google-Maps-iOS-Utils/GMUPlacemark.h>
-#import <Google-Maps-iOS-Utils/GMUPoint.h>
-#import <Google-Maps-iOS-Utils/GMUGeometryRenderer.h>
+#import "GMUKMLParser.h"
+#import "GMUPlacemark.h"
+#import "GMUPoint.h"
+#import "GMUGeometryRenderer.h"
 #define REQUIRES_GOOGLE_MAPS_UTILS(feature) do {} while (0)
 #else
 #define GMUKMLParser void
diff --git a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h
index 20faf23..e1a1549 100644
--- a/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h
+++ b/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapHeatmap.h
@@ -4,14 +4,14 @@
 //  Created by David Cako on 29 April 2018.
 //
 
-#import <Google-Maps-iOS-Utils/GMUHeatmapTileLayer.h>
+#import "GMUHeatmapTileLayer.h"
 
 @interface AIRGoogleMapHeatmap : UIView
 
-@property (nonatomic, strong) GMUHeatmapTileLayer *heatmap;
-@property (nonatomic, strong) NSMutableArray<GMUWeightedLatLng *> *points;
-@property (nonatomic, assign) NSUInteger radius;
-@property (nonatomic, assign) float opacity;
-@property (nonatomic, assign) GMUGradient *gradient;
+@property(nonatomic, strong) GMUHeatmapTileLayer *heatmap;
+@property(nonatomic, strong) NSMutableArray<GMUWeightedLatLng *> *points;
+@property(nonatomic, assign) NSUInteger radius;
+@property(nonatomic, assign) float opacity;
+@property(nonatomic, assign) GMUGradient *gradient;
 
 @end
diff --git a/node_modules/react-native-maps/package.json b/node_modules/react-native-maps/package.json
index 873c1a7..11f5eaf 100644
--- a/node_modules/react-native-maps/package.json
+++ b/node_modules/react-native-maps/package.json
@@ -20,8 +20,7 @@
     "lib",
     "android",
     "ios",
-    "react-native-google-maps.podspec",
-    "react-native-maps.podspec",
+    "RNMaps.podspec",
     "!android/build",
     "!ios/build",
     "!**/__tests__",
diff --git a/node_modules/react-native-maps/react-native-google-maps.podspec b/node_modules/react-native-maps/react-native-google-maps.podspec
deleted file mode 100644
index f619189..0000000
--- a/node_modules/react-native-maps/react-native-google-maps.podspec
+++ /dev/null
@@ -1,22 +0,0 @@
-require 'json'
-
-package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
-
-Pod::Spec.new do |s|
-  s.name         = "react-native-google-maps"
-  s.version      = package['version']
-  s.summary      = package["description"]
-  s.authors      = package["author"]
-  s.homepage     = package["homepage"]
-  s.license      = package["license"]
-  s.platform     = :ios, "13.0"
-
-  s.source       = { :git => "https://github.com/react-native-maps/react-native-maps.git", :tag=> "v#{s.version}" }
-  s.source_files  = "ios/AirGoogleMaps/**/*.{h,m}"
-  s.compiler_flags = '-DHAVE_GOOGLE_MAPS=1', '-DHAVE_GOOGLE_MAPS_UTILS=1', '-fno-modules'
-  s.pod_target_xcconfig = { "HEADER_SEARCH_PATHS" => "$(inherited) '$(PODS_ROOT)/Google-Maps-iOS-Utils/src/Heatmap' '$(PODS_ROOT)/Headers/Public/'" }
-
-  s.dependency 'React-Core'
-  s.dependency 'GoogleMaps', '7.0.0'
-  s.dependency 'Google-Maps-iOS-Utils', '4.1.0'
-end
diff --git a/node_modules/react-native-maps/react-native-maps.podspec b/node_modules/react-native-maps/react-native-maps.podspec
deleted file mode 100644
index b0cd103..0000000
--- a/node_modules/react-native-maps/react-native-maps.podspec
+++ /dev/null
@@ -1,18 +0,0 @@
-require 'json'
-
-package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
-
-Pod::Spec.new do |s|
-  s.name         = "react-native-maps"
-  s.version      = package['version']
-  s.summary      = package["description"]
-  s.authors      = package["author"]
-  s.homepage     = package["homepage"]
-  s.license      = package["license"]
-  s.platform     = :ios, "11.0"
-
-  s.source       = { :git => "https://github.com/react-native-maps/react-native-maps.git", :tag=> "v#{s.version}" }
-  s.source_files  = "ios/AirMaps/**/*.{h,m}"
-
-  s.dependency 'React-Core'
-end
```

This plugin is optional if you don't use Google Maps on iOS.
Filename: `withReactNativeMaps.plugin.js`
```js
const fs = require('fs');
const path = require('path');
const generateCode = require('@expo/config-plugins/build/utils/generateCode');
const configPlugins = require('@expo/config-plugins');

const withReactNativeMaps = (config) => {
  return configPlugins.withDangerousMod(config, [
    'ios',
    async (config) => {
      const filePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      const contents = await fs.promises.readFile(filePath, 'utf-8');
      let results;
      try {
        results = generateCode.mergeContents({
          // We need to use the same tag as expo/config-plugins uses to find the
          // correct place to insert the code.
          // It remove the old code and insert the new code.
          tag: 'react-native-maps',
          src: contents,
          newSrc: '  $RNMapsWithGoogleMapsSupport = true',
          anchor: /use_native_modules/,
          offset: 0,
          comment: '#',
        });
      } catch (err) {
        if (err.code === 'ERR_NO_MATCH') {
          throw new Error(
            `Cannot add react-native-maps to the project's ios/Podfile because it's malformed. `+
            'Please report this with a copy of your project Podfile.'
          );
        }
        throw err;
      }
      if (results.didMerge) {
        await fs.promises.writeFile(filePath, results.contents);
      }
      return config;
    },
  ]);
};

module.exports = withReactNativeMaps;
```

**Pull request closed without merging**
