### PR TITLE
[iOS] Update Google-Maps-iOS-Utils to 4.2.2 to officialy support Apple Silicon without Rosetta

### PR DESCRIPTION
**Pull request by lorenc-tomasz**
### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

https://github.com/react-native-maps/react-native-maps/issues/4754

### How did you test this PR?

Tested on iOS from 13 to 16.5.1. 
App built on Intel and Apple Silicon machines.

### CODE REVIEW

**Review by cixio — APPROVED** [review]
Thanks! Works like a charm.

**Review by kmanuel67 — APPROVED** [review]

**Comment by kmanuel67** [comment]
This worked for me too on my M1 Mac.

**Comment by lorenc-tomasz** [comment]
Hi,
@Simon-TechForm could you look into this PR, please?

**Comment by lorenc-tomasz** [comment]
@Madhu02 Try to patch `react-native-google-places` yourself as it's really old package.

**Comment by Nodonisko** [comment]
Works like a charm, finally able to build app with GMaps. Can we merge this?

**Comment by Simon-TechForm** [comment]
Hi @lorenc-tomasz, thank you for opening this 👍

I've just [opened a PR](https://github.com/googlemaps/google-maps-ios-utils/pull/451) that I would like to see merged and released before we bump `google-maps-ios-utils` in `react-native-maps`.

`google-maps-ios-utils@v4.2.2` (or rather v4.2.0) introduced a [version range requirement](https://github.com/googlemaps/google-maps-ios-utils/compare/v4.1.0...v4.2.0#diff-f028a3ce88c2e400b7dc05ec2a5105d86a79d7b9e15303aebbc2a0b110d2e3b4R24) that has already resulted in `google-maps-ios-utils` being incompatible with the latest version of the Google Maps SDK for iOS.

Once that's released, hopefully you will be up for updating this PR and I'll be happy to review and merge it 🚀

Meanwhile, the workaround mentioned in the [installation docs](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps) should do the trick (and doesn't include the version range requirement).

**Comment by SohelIslamImran** [comment]
Is this https://github.com/react-native-maps/react-native-maps/issues/4793 issue related to this PR?

**Comment by SohelIslamImran** [comment]
> Meanwhile, the workaround mentioned in the [installation docs](https://github.com/react-native-maps/react-native-maps/blob/master/docs/installation.md#enabling-google-maps) should do the trick (and doesn't include the version range requirement).

This plugin will do the trick for Expo/EAS.

```js
// react-native-maps-plugin.js
const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("expo/config-plugins");
const generateCode = require("@expo/config-plugins/build/utils/generateCode");

// https://github.com/react-native-maps/react-native-maps/issues/4793#issuecomment-1671269814
const googleMapsIosSiliconWorkaroundPodCode = `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/Simon-TechForm/google-maps-ios-utils.git', :branch => 'feat/support-apple-silicon'`;

/** @type { import('expo/config-plugins').ConfigPlugin } */
const withPlugin = (expoConfig) => {
  return withDangerousMod(expoConfig, [
    "ios",
    async (config) => {
      const filePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      const contents = fs.readFileSync(filePath, "utf-8");

      const addCode = generateCode.mergeContents({
        newSrc: googleMapsIosSiliconWorkaroundPodCode,
        tag: "withGoogleMapsIOSWorkaroundPlugin",
        anchor: /\s*get_default_flags\(\)/i,
        src: contents,
        comment: "#",
        offset: 2,
      });

      if (!addCode.didMerge) {
        console.warn(
          "WARNING: Couldn't add custom plugin Podfile code from app.plugin.js to the project's ios/Podfile."
        );
        return config;
      }

      fs.writeFileSync(filePath, addCode.contents);

      return config;
    },
  ]);
};

module.exports = withPlugin;
```

```json
// app.json
"plugins": [
      "./react-native-maps-plugin",
    ],
```

**Comment by premdasvm** [comment]
@SohelIslamImran Thanks mate, That worked like a charm.

**Comment by erickreutz** [comment]
LGTM!

**Review by fobos531 — APPROVED** [review]

**Review by salah-ghanim — APPROVED** [review]
LGTM

**Pull request merged**
