### PR TITLE
ios fix

### PR DESCRIPTION
**Pull request by devuco**
Does any other open PR do the same thing?
Not sure about other PRs

What issue is this PR fixing?
iOS build fails as the import paths are relative in AirGoogleMap.m instead of absolute so fixed that issue

How did you test this PR?
This takes effect on iOS. Tested on both real device and simulator.

### CODE REVIEW

**Comment by SohelIslamImran** [comment]
Is this related to https://github.com/react-native-maps/react-native-maps/issues/4563 ? Can anyone please work on it and merge it quickly!? This issue is from a long time.

**Comment by izniburak** [comment]
Is there any plan to merge this PR? This issue must be fixed.

**Comment by devuco** [comment]
Please use this fork until this PR is merged https://github.com/infoSamyak/react-native-maps/tree/master

**Comment by infoSamyak** [comment]
@Simon-TechForm Please suggest

**Comment by izniburak** [comment]
> Please use this fork until this PR is merged https://github.com/infoSamyak/react-native-maps/tree/master

I've tried it but it didn't work. Do you have any suggestion to use this fork?

**Comment by devuco** [comment]
> > Please use this fork until this PR is merged https://github.com/infoSamyak/react-native-maps/tree/master
> 
> I've tried it but it didn't work. Do you have any suggestion to use this fork?

What issue are you facing?

**Comment by Simon-TechForm** [comment]
Hello @devuco 👋

Are you able to establish a couple of test cases for this?

The current PR contains very limited context regarding when this an issue/when the pr fixes the issue. Personally I've never experienced the issue put forward. So we need to establish a baseline for when this error might show, and in what cases this will fix it :) Once we do, I'm more than happy to merge this 👍

**Review by MadeinFrance — APPROVED** [review]
This fixes when the Pods are configured with statically linked Frameworks.

Thanks 👍

**Comment by Simon-TechForm** [comment]
@MadeinFrance are you using Expo or vanilla react-native? :)

**Comment by MadeinFrance** [comment]
Hi, @Simon-TechForm thank you for maintaining this library, many of us depend on it (including myself) 
I'm using vanilla react-native and this issue is reproducible. Additionally, it was mentioned in this other issue #4552

**Comment by devuco** [comment]
> This fixes when the Pods are configured with statically linked Frameworks.
> 
> Thanks 👍

Thank You @MadeinFrance for the comment.
@Simon-TechForm As mentioned above the issue is faced when we use 'use_frameworks! :linkage => :static' in podfile.

Please ask any further questions if required.
Thank You

**Comment by Simon-TechForm** [comment]
@devuco @MadeinFrance 👍

I've updated the CI checks to include a build using frameworks 🤞

**Comment by Simon-TechForm** [comment]
It seems like this change in itself doesn't allow building with `use_frameworks` 😞

Any chance you made other changes in your local projects that might allow it to build?

**Review by MadeinFrance — CHANGES_REQUESTED** [review]
Currently, this breaks building the project as @Simon-TechForm has shown in the GitHub workflow.

**Comment by Simon-TechForm** [comment]
See: #4678

Let me know if you get a chance to test out the chances, should allow `use_frameworks! :linkage => :static` without any other changes (remember to clean, reinstall etc. pods). Here's hoping the CI will turn green 🤞

**Pull request closed without merging**
