### PR TITLE
fix for URLTile shouldReplaceMapContent

### PR DESCRIPTION
**Pull request by cixio**
### Does any other open PR do the same thing?

no

### What issue is this PR fixing?

https://github.com/react-native-maps/react-native-maps/issues/4458

### How did you test this PR?

iPhone Simulator + iPhone 14 Pro

```
      <MapView
        style={{width:"100%", height:"100%"}}
        showsScale={true}
        initialCamera={{
          center: {
            latitude: 52,
            longitude: 10,
          },
          heading: 5,
          altitude: 26900,
        }}
        provider={PROVIDER_DEFAULT}
        mapType={"standard"}
      >
        <UrlTile
          urlTemplate={"https://b.tile.openstreetmap.de/{z}/{x}/{y}.png"}
          maximumZ={19}
          shouldReplaceMapContent={true} 
        />  
      </MapView>
```

Result: Apple Maps are not longer in Background of the map and labels are not longer visible above the UrlTile-Map.

### CODE REVIEW

**Comment by stdavis** [comment]
This solves #4458 for me. Thanks, @cixio! 🙌

**Comment by Simon-TechForm** [comment]
@cixio thank your for putting this together and thank you @stdavis trying it out and providing feedback 👍

@stdavis is iOS 15 and iOS 16 behaving identically when trying out this change? I'm a little confused as to why this started acting up in iOS 16 without any release notes from Apple 😕 (`MKOverlayLevelAboveLabels` was added in iOS 7 after all...)

I'm considering whether we would need to add this as an option instead of forcing it on every consumer. While using `MKOverlayLevelAboveLabels` might be desired if using tiles that includes labels and POI's, some consumers might rely on these actually being shown all the time.

**Comment by stdavis** [comment]
> is iOS 15 and iOS 16 behaving identically when trying out this change?

Yes. It broke at 16 for me.

> I'm considering whether we would need to add this as an option instead of forcing it on every consumer.

I think that you may be on to something. My tiles have labels baked in, but I can see users who are using plain imagery wanting the labels to show up on top.

**Comment by Simon-TechForm** [comment]
> I think that you may be on to something. My tiles have labels baked in, but I can see users who are using plain imagery wanting the labels to show up on top.

Exactly. I don't think this can be merged as is.

If either of you are able to work on a solution that provides this setting as a prop, I'll be happy to provide feedback and review :)

**Comment by stdavis** [comment]
> If either of you are able to work on a solution that provides this setting as a prop, I'll be happy to provide feedback and review

I took a stab at it: https://github.com/react-native-maps/react-native-maps/pull/4725

**Comment by cixio** [comment]
Still relevant in combination with https://github.com/react-native-maps/react-native-maps/pull/4725

**Comment by salah-ghanim** [comment]
@cixio thank you for this pull request, I'm trying to merge it but I see somethings need to be addressed first:

1. I suggested to @stdavis an alternative implementation and waiting on his feedback, so any changes regarding the tiles / layers order need to wait on that discussion because him and @monholm highlighted a good point regarding other users of the library.

2. I see that you fixed a crash for removing a layer on android, can you please submit a pull request specifically for that issue, that way it can be quickly merged regardless of this discussion.

3. I see that you added a note regarding an issue of auto-tracking user, but I don't see the change for it in in the code.

**Pull request closed without merging**
