### PR TITLE
feat(AIRGoogleMapsMarker): add onSelect/onDeselect support fo google maps

### PR DESCRIPTION
**Pull request by jan-kozinski**
### Does any other open PR do the same thing?

no

### What issue is this PR fixing?

https://github.com/react-native-maps/react-native-maps/issues/4970

https://github.com/react-native-maps/react-native-maps/issues/114
### How did you test this PR?

andoid emulator & ios simulator

### CODE REVIEW

**Comment by EJohnF** [comment]
Wow! i was looking for this functionality, and you just pushed it 🎉

**Review by mateki0 — APPROVED** [review]
Looks and works fine on iOS simulator and Android device. I'm just thinking if second press on the same marker shouldn't be considered as deselect on iOS. It works like that on Android though.

**Comment by jan-kozinski** [comment]
Thanks @mateki0 good catch! I've tweaked the google maps implementation to match the mapkit one's. So no it should be impossible to deselect a marker by clicking on it multiple times

**Comment by salah-ghanim** [comment]
@jan-kozinski the code looks good, but I have a small feedback

I wouldn't change the AIRGoogleMapMarker.m eventFromMarker AIRGMSMarker.m for some reason that class was left empty all the history of the repo, I would simply keep the same tradition.

instead just modify the function in AIRGoogleMapMarker to accept action as a parameter, for example:

```
eventFromMarker: marker action:(_Nullable NSString *) action {
}
```

finally, In general I would avoid adding anything to the .h files, because that implies new public interfaces / functionality ... I don't see the need for such APIs most of the time, rather the body of a class (.m file) can manage the state internally and propagate the events correctly as you can see.

**Comment by jan-kozinski** [comment]
Hi @salah-ghanim thanks for the feedback. I've added the makeEventData to the AIRGMSMarker, because selectedMarker in AIRGoogleMap must ba an instance of GSMMarker (it can't be a AIRGoogleMapMarker because the  `[super setSelectedMarker:selectedMarker];` expects a AIRGMSMarker. 
Still, I wanted both classes to use the same method for event generating as to avoid incosistent marker events in future.
I think the reason for AIRGMSMarker.m to be left empty is that it simply didn't require any functionality in the past. I don't consider it an intentinal action as there is no comment that would document such decision

**Comment by jan-kozinski** [comment]
Also thanks for the advice with .h files, I've removed as many public interfaces as possible. Removing them further causes the code to not compile.

**Review by salah-ghanim — APPROVED** [review]

**Pull request merged**
