### PR TITLE
Document that the `isGesture` property is supported by Google Maps only

### PR DESCRIPTION
**Pull request by juice49**
### Does any other open PR do the same thing?

No.

### What issue is this PR fixing?

Documentation.

### How did you test this PR?

Previewed the Markdown file.

### CODE REVIEW

**Comment by rborn** [comment]
😻

**Comment by Dallas62** [comment]
Jumping into this PR to ask:
How is it possible to intercept this parameter (`isGesture`) on iOS ?
I look into the API but it's seems that no other event listener allow us to catch user interaction.
Thanks by advance !

**Comment by yairopro** [comment]
Hi @Dallas62 
I don't understand your question.
If you want to intercept `isGesture`, just listen to `onRegionChange(Complete)`. What other event should have this parameter ?

**Comment by Dallas62** [comment]
Hi, yes sorry didn't saw GoogleMap only and not released yet, works on master.

**Comment by Infinitism** [comment]
This doesn't work on v0.27.1! I am using Google Maps and the "isGesture" is not defined at all for onRegionChangeComplete.

**Comment by yairopro** [comment]
Because it hasn't been released yet.
If you check the v0.27.1 tag, it doesn't include the commit.

**Comment by Infinitism** [comment]
Got it! It was confusing since the documentation listed it. Do we know when it'll be released?

**Pull request merged**
